[project]
name = "project02"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "openai>=1.90.0",
    "pypdf2>=3.0.1",
    "streamlit>=1.46.0",
]
